# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bibdb < Formula
  desc "Git-backed BibTeX database manager"
  homepage "https://github.com/yareeh/bibdb"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yareeh/bibdb/releases/download/v1.1.0/bibdb_darwin_amd64.tar.gz"
      sha256 "55fa23167b938a3179344f8bdf893d5b09d9830944244d89acf5c6193abfad89"

      define_method(:install) do
        bin.install "bibdb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yareeh/bibdb/releases/download/v1.1.0/bibdb_darwin_arm64.tar.gz"
      sha256 "945c1fe68c3250e123d0dce8c13098e8c0949c27385040edecd9d5bf7a0b0785"

      define_method(:install) do
        bin.install "bibdb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yareeh/bibdb/releases/download/v1.1.0/bibdb_linux_amd64.tar.gz"
      sha256 "86042773c80425980c19abec4696fd29dfb0715eb6ab027fe4c521c8907384d2"
      define_method(:install) do
        bin.install "bibdb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yareeh/bibdb/releases/download/v1.1.0/bibdb_linux_arm64.tar.gz"
      sha256 "fc74716a880819efd41eb34ab3825f07b459ba91fd955229229d74a1ace4bc8f"
      define_method(:install) do
        bin.install "bibdb"
      end
    end
  end
end
