# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bibdb < Formula
  desc "Git-backed BibTeX database manager"
  homepage "https://github.com/yareeh/bibdb"
  version "1.4.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yareeh/bibdb/releases/download/v1.4.4/bibdb_darwin_amd64.tar.gz"
      sha256 "d6a364d16d6e69bfb8c7eb02cd3785440e34048bbd5b7664b2ef4d8dc404d5f2"

      define_method(:install) do
        bin.install "bibdb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yareeh/bibdb/releases/download/v1.4.4/bibdb_darwin_arm64.tar.gz"
      sha256 "c9d9b70735acea2684c2d9c3d123592d091e84be3e3a42edc3efb128cbd17299"

      define_method(:install) do
        bin.install "bibdb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yareeh/bibdb/releases/download/v1.4.4/bibdb_linux_amd64.tar.gz"
      sha256 "6c00f682c84d706247b16b5f75c60c8cd65276796391c58a15e9d5803df5926c"
      define_method(:install) do
        bin.install "bibdb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yareeh/bibdb/releases/download/v1.4.4/bibdb_linux_arm64.tar.gz"
      sha256 "c9cd39bd25499df58f910397adc58fc3f19ced2c3a09782129ccab787572d3ae"
      define_method(:install) do
        bin.install "bibdb"
      end
    end
  end
end
