# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bibdb < Formula
  desc "Git-backed BibTeX database manager"
  homepage "https://github.com/yareeh/bibdb"
  version "1.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yareeh/bibdb/releases/download/v1.3.1/bibdb_darwin_amd64.tar.gz"
      sha256 "848f2152f44b138db4755b65bc11aa085855838526e4671ef779776b77a64c46"

      define_method(:install) do
        bin.install "bibdb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yareeh/bibdb/releases/download/v1.3.1/bibdb_darwin_arm64.tar.gz"
      sha256 "4ed5d8703cd4fe7e8556f4a7caee1fdf3e9ba1b82758a13e4f6c45716e0077dd"

      define_method(:install) do
        bin.install "bibdb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yareeh/bibdb/releases/download/v1.3.1/bibdb_linux_amd64.tar.gz"
      sha256 "535177f8100964b7b64e6e21490cced028c2487a5378fbfe9026de3af0769dee"
      define_method(:install) do
        bin.install "bibdb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yareeh/bibdb/releases/download/v1.3.1/bibdb_linux_arm64.tar.gz"
      sha256 "e80c4015af8e9447578a82529834b702936563719c5822e078add01a44f70e13"
      define_method(:install) do
        bin.install "bibdb"
      end
    end
  end
end
