# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoodreadsCli < Formula
  desc "CLI for Goodreads with browser automation for login and shelf operations"
  homepage "https://github.com/yareeh/goodreads-cli"
  version "1.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yareeh/goodreads-cli/releases/download/v1.5.0/goodreads-cli_darwin_amd64.tar.gz"
      sha256 "e97adeee008ce72d6eff6c872ddbb23abd3c87a901ef561869973aa7881e587a"

      define_method(:install) do
        bin.install "goodreads-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yareeh/goodreads-cli/releases/download/v1.5.0/goodreads-cli_darwin_arm64.tar.gz"
      sha256 "ac618dcca9f4479e98ec2647b640274b2470ff1160f4fef6aaee49d585aa208d"

      define_method(:install) do
        bin.install "goodreads-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yareeh/goodreads-cli/releases/download/v1.5.0/goodreads-cli_linux_amd64.tar.gz"
      sha256 "78bd9cc7371bef2ac1d122b380ef7dfb7e8ae991d5ed7f860e412725b4487035"
      define_method(:install) do
        bin.install "goodreads-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yareeh/goodreads-cli/releases/download/v1.5.0/goodreads-cli_linux_arm64.tar.gz"
      sha256 "0cd69ab66d0bdb659aa3052c63286b6816c3940dfb7e537f1b9c487885c43dba"
      define_method(:install) do
        bin.install "goodreads-cli"
      end
    end
  end
end
