# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoodreadsCli < Formula
  desc "CLI for Goodreads with browser automation for login and shelf operations"
  homepage "https://github.com/yareeh/goodreads-cli"
  version "1.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yareeh/goodreads-cli/releases/download/v1.4.0/goodreads-cli_darwin_amd64.tar.gz"
      sha256 "618924fbaaffc00af28d396b8d83c74cb1a7fdca80493d1423fd99355ca4808f"

      define_method(:install) do
        bin.install "goodreads-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yareeh/goodreads-cli/releases/download/v1.4.0/goodreads-cli_darwin_arm64.tar.gz"
      sha256 "573230de951aa326afdbc0d769e8fe9fcb44f781ae72d87585048ad04bb8d5af"

      define_method(:install) do
        bin.install "goodreads-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yareeh/goodreads-cli/releases/download/v1.4.0/goodreads-cli_linux_amd64.tar.gz"
      sha256 "fb8f49768ad4a0a50d708de05f1ad7faecda701d70a1189b68d32db7303e85e1"
      define_method(:install) do
        bin.install "goodreads-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yareeh/goodreads-cli/releases/download/v1.4.0/goodreads-cli_linux_arm64.tar.gz"
      sha256 "b80e098dfdded77ab60283206b08bf18904002692481c9faaba402b32d03c906"
      define_method(:install) do
        bin.install "goodreads-cli"
      end
    end
  end
end
