# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoodreadsCli < Formula
  desc "CLI for Goodreads with browser automation for login and shelf operations"
  homepage "https://github.com/yareeh/goodreads-cli"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yareeh/goodreads-cli/releases/download/v1.1.0/goodreads-cli_darwin_amd64.tar.gz"
      sha256 "ebecb0ae073d7ed78b36b43530f4b6c469c0ce0a7b5266a45b9b335b12d62ce0"

      define_method(:install) do
        bin.install "goodreads-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yareeh/goodreads-cli/releases/download/v1.1.0/goodreads-cli_darwin_arm64.tar.gz"
      sha256 "5e179f950c53ac3698c8768e2821f9479674ca98e72e9cf7917022b33b5173e4"

      define_method(:install) do
        bin.install "goodreads-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yareeh/goodreads-cli/releases/download/v1.1.0/goodreads-cli_linux_amd64.tar.gz"
      sha256 "6fef68c1d2f28d73642caa82302d4c35496e8e8f1860e5923c4015dd6f96e1b6"
      define_method(:install) do
        bin.install "goodreads-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yareeh/goodreads-cli/releases/download/v1.1.0/goodreads-cli_linux_arm64.tar.gz"
      sha256 "153d405f8b85763d1956c6fc7ecdc391a93f6d982b8ee3fafa54fbf602670075"
      define_method(:install) do
        bin.install "goodreads-cli"
      end
    end
  end
end
