# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ThemoviedbCli < Formula
  desc "CLI for The Movie Database (TMDB), designed for agentic use with AI assistants"
  homepage "https://github.com/yareeh/themoviedb-cli"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yareeh/themoviedb-cli/releases/download/v1.0.0/themoviedb-cli_darwin_amd64.tar.gz"
      sha256 "435cb32c3e9677fab4eff571047acc4d9c6b427e4c020d5853fda399824a96f0"

      def install
        bin.install "themoviedb-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yareeh/themoviedb-cli/releases/download/v1.0.0/themoviedb-cli_darwin_arm64.tar.gz"
      sha256 "ecc1652ed65821d9035ca1134549b1cd86ebec6c0aae8e2af56aca081d08b66d"

      def install
        bin.install "themoviedb-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yareeh/themoviedb-cli/releases/download/v1.0.0/themoviedb-cli_linux_amd64.tar.gz"
      sha256 "d30339e5811c6fe921dd3ef891943a668c8f9177cefd745506440facfc198f26"
      def install
        bin.install "themoviedb-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yareeh/themoviedb-cli/releases/download/v1.0.0/themoviedb-cli_linux_arm64.tar.gz"
      sha256 "31b04617844bffe32babdb34c6273059b2070cb88f89b6cdfb01412ccc8547e9"
      def install
        bin.install "themoviedb-cli"
      end
    end
  end
end
